apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
    - port: {{ .Values.n8n.port }}
      targetPort: {{ .Values.n8n.port }}
      nodePort: 30080
