n8n:
  image: n8nio/n8n
  tag: latest
  port: 5678
  mountPath: /home/node/.n8n
  volumePath: /mnt/data/n8n

postgres:
  image: postgres
  tag: 17
  port: 5432
  database: n8ndb
  host: postgres
  user: n8n
  mountPath: /var/lib/postgresql/data
  volumePath: /mnt/data/postgres
  password: n8npass
